###

GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
 "tipoMascota": "Perro",
 "estadoMascota": "Perdido",
 "nombreMascota": "Prueba 5",
 "sexoMascota": "Macho",
 "descripcionMascota": "Es miedoso 2",
 "chipMascota": "No",
 "fechaMascota": "",
 "departamentoPerdidoMascota": "Montevideo",
 "localidadPerdidoMascota": "Cerro",
 "lugarPerdidoMascota": "Cibils y Alianza",
 "nombreResponsableMascota": "Carlos",
 "descripcionResponsableMascota": "Llamen al 099123456",
 "viralInfo": "Perro perdido en Montevideo, Brazo Oriental, más específicamente en: Cerrito esq Quesas Responde al nombre de Prueba 1, raza no especificada. Tiene chip. Datos de vital importancia: Es miedoso. . No cuesta NADA compartir. La calle no es hogar para nadie... #Uruguay #Montevideo #AnimalPerdido #SeBusca"
}

###
DELETE http://localhost:9000/api/13 HTTP/1.1

###
PUT http://localhost:9000/api/15 HTTP/1.1
Content-Type: application/json

{
 "tipoMascota": "Perro",
 "estadoMascota": "Perdido",
 "nombreMascota": "Prueba 6",
 "sexoMascota": "Macho",
 "descripcionMascota": "Es miedoso 2",
 "chipMascota": "No",
 "fechaMascota": "",
 "departamentoPerdidoMascota": "Montevideo",
 "localidadPerdidoMascota": "Cerro",
 "lugarPerdidoMascota": "Cibils y Alianza",
 "nombreResponsableMascota": "Carlos",
 "descripcionResponsableMascota": "Llamen al 099123456",
 "viralInfo": "Perro perdido en Montevideo, Brazo Oriental, más específicamente en: Cerrito esq Quesas Responde al nombre de Prueba 1, raza no especificada. Tiene chip. Datos de vital importancia: Es miedoso. . No cuesta NADA compartir. La calle no es hogar para nadie... #Uruguay #Montevideo #AnimalPerdido #SeBusca"
}